const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = { console, clearTimeout, app: { registerModule(name, members) { Object.assign(this, members); } } };
vm.createContext(context);
for (const file of ['utils', 'workspace/03-strategy', 'workspace/04-stage']) {
  vm.runInContext(fs.readFileSync(`frontend/js/${file}.js`, 'utf8') + (file === 'utils' ? '\nglobalThis.Utils = Utils;' : ''), context);
}
const {app, Utils} = context;
let stage = {skuNames: ['A','B','C'], bom: [{materialName:'屏幕',sku1:'A屏',sku2:'B屏',sku3:'C屏'}, {materialName:'存储',sku3:'256GB'}], strategy:[{skuMap:{1:true,2:false,3:true}}], progress:[{skuIndex:1},{skuIndex:2},{skuIndex:3}]};
app.currentStage = () => stage;
app.render = () => {};
let saves = [];
app.scheduleStageStrategySave = (...args) => saves.push(args);
context.document = { querySelectorAll: () => [], createTextNode: text => text };
Utils.toast = () => {};
const html = app.workspaceBomHtml(stage);
assert.match(html, /<thead>[\s\S]*value="屏幕"[\s\S]*value="存储"[\s\S]*<\/thead>/);
assert.match(html, /data-index="0" data-field="sku3">C屏/);
assert.match(html, /data-index="1" data-field="sku3">256GB/);
assert.equal((html.match(/<th scope="row"/g)||[]).length, 3);
for (const count of [0, 1, 2, 3, 4, 5]) {
  const record = {skuNames:['A','B'], bom:Array.from({length:count}, () => ({materialName:''}))};
  const before = JSON.stringify(record);
  const matrix = app.workspaceBomHtml(record);
  assert.equal((matrix.match(/<col style="width:200px">/g) || []).length, Math.max(4,count));
  assert.equal((matrix.match(/<th scope="col" class="scheme-bom-placeholder"/g) || []).length, Math.max(0,4-count));
  assert.equal((matrix.match(/<td class="scheme-bom-placeholder"/g) || []).length, Math.max(0,4-count)*2);
  assert.equal((matrix.match(/<textarea/g) || []).length, count*2);
  assert.equal(JSON.stringify(record), before, 'empty slots must not create material records');
}
app.renameMatrixSku(1, {value:'A'});
assert.equal(stage.skuNames[1], 'B');
app.renameMatrixSku(1, {value:''});
assert.equal(stage.skuNames[1], 'B');
app.renameMatrixSku(1, {value:'新方案'});
assert.equal(stage.bom[0].sku2, 'B屏');
assert.equal(stage.skuNames[1], '新方案');
app.addMatrixSku();
assert.equal(stage.skuNames.length, 4);
assert.equal(stage.bom[0].sku4, undefined);
stage.skuNames.pop();
let confirmation;
app.showConfirm = (text, callback) => { confirmation = callback; };
app.persistStageStrategyMutation = async () => true;
(async () => {
  app.removeMatrixSku(1); await confirmation();
  assert.deepEqual(Array.from(stage.skuNames), ['A','C']);
  assert.equal(stage.bom[0].sku2,'C屏');
  assert.equal(stage.bom[1].sku2,'256GB');
  assert.equal(stage.bom[0].sku3,undefined);
  assert.equal(stage.strategy[0].skuMap[2],true);
  assert.deepEqual(Array.from(stage.progress, row => row.skuIndex),[1,2]);
  const before = JSON.stringify(stage);
  app.persistStageStrategyMutation = async () => false;
  app.removeMatrixSku(0); await confirmation();
  assert.equal(JSON.stringify(stage), before, 'failed saves restore scheme and all linked cells');
  // Creating a stage starts with four independent, editable material columns.
  const project = { stages: [] };
  let submit;
  app.showModal = (_title, _html, callback) => { submit = callback; };
  app.currentProject = () => project;
  app.clearFieldValidationMarks = () => {};
  app.dataSnapshot = () => ({});
  app.readSkuInputs = () => ['A', 'B'];
  app.selectStageAfterMutation = () => {};
  app.commitStageMutation = async () => true;
  context.document.getElementById = () => ({ value: 'EVT' });
  app.addStage();
  await submit();
  const created = project.stages[0];
  assert.equal(created.bom.length, 4);
  created.bom[0].materialName = '屏幕';
  assert.equal(created.bom[1].materialName, '');
  assert.equal((app.workspaceBomHtml(created).match(/data-field="materialName"/g) || []).length, 4);
  console.log('scheme/BOM matrix mapping and rollback passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
