const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const copy = x => JSON.parse(JSON.stringify(x));
const context = { console, setTimeout, document: {}, app: { registerModule(_, methods) { Object.assign(this, methods); } } };
vm.createContext(context);
for (const module of ['utils', 'app.data', 'samples/05-problems', 'samples/05-problem-photos', 'workspace/09-task-result']) {
  vm.runInContext(fs.readFileSync(path.join(__dirname, '../frontend/js', module + '.js'), 'utf8') + (module === 'utils' ? '\nglobalThis.Utils=Utils;' : ''), context);
}
const app = context.app;
app.sampleTaskLabelFromCtx = () => '项目 / V3 / 测试';
const sample = { id: 's', problemRecords: [] };
app.findSample = () => ({ sample });
const photos = [{ id: 'photo_A', name: 'same.png' }, { id: 'photo_B', name: 'same.png' }];
const input = { sid: 's', problem: '黑斑', problemRecords: [], photos };
const task = {};
app.saveTaskResultDraft({ id: 'p' }, { id: 'stage' }, task, { samples: [input] });
const draft = task.resultDraft.samples[0];
assert.equal(sample.problemRecords.length, 0, 'draft must not change sample archive');
assert.deepEqual(copy(draft.problemRecords[0].photoIds), ['photo_A', 'photo_B']);
assert.equal(draft.problem, '');
assert.deepEqual(copy(draft.photos), [], 'images move with their problem, never leak to the next problem');
const id = draft.problemRecords[0].id;
const finished = app.syncTaskResultSampleProblems(sample, draft, { taskId: 'task' });
assert.equal(finished[0].id, id);
assert.deepEqual(copy(sample.problemRecords[0].photoIds), ['photo_A', 'photo_B']);
const duplicate = app.syncTaskResultSampleProblems(sample, { ...draft, problem: '黑斑', photos: [{ id: 'photo_C' }, photos[0]] });
assert.equal(duplicate.length, 1);
assert.deepEqual(copy(duplicate[0].photoIds), ['photo_A', 'photo_B', 'photo_C']);
const before = { samples: [{ ...draft, photos: [] }] };
const after = copy(before);
after.samples[0].problemRecords[0].photoIds = ['photo_B'];
assert.equal(app.isTaskResultSamplesEqual(before, after), false, 'attachment-only edits must save');
assert.equal(app.isTaskResultSamplesEqual(before, copy(before)), true);
const legacy = { samples: [{ sid: 's', problem: '', photos, problemRecords: [{ id: 'old', description: '旧问题' }] }] };
app.saveTaskResultDraft({ id: 'p' }, { id: 'stage' }, task, legacy);
assert.equal(task.resultDraft.samples[0].problemRecords[0].photoIds, undefined, 'do not guess old associations');
assert.equal(task.resultDraft.samples[0].photos.length, 2);
const record = { id: 'stable', description: '问题', source: '初检', provenance: { original: true }, photoIds: ['photo_A'] };
const fields = { '.sample-problem-desc': { value: '改名' }, '.sample-problem-source': { value: '初检' }, '.sample-problem-task': { value: '' } };
const link = { textContent: '' };
const row = { dataset: { problemId: 'stable', problemRecord: JSON.stringify(record) }, classList: { contains: () => false }, querySelector: s => fields[s] || (s.startsWith('[data-app-action') ? link : null) };
app.setProblemRowPhotoIds(row, ['photo_B', 'photo_B']);
const saved = app.problemRecordFromElement(row);
assert.equal(saved.description, '改名');
assert.equal(saved.id, 'stable');
assert.equal(saved.provenance.original, true);
assert.deepEqual(copy(saved.photoIds), ['photo_B']);
assert.equal(link.textContent, '查看图片（1）');
app.setProblemRowPhotoIds(row, []);
assert.equal(link.textContent, '添加图片');
const baseline = [{ id: 'p', description: 'old', source: '初检', photoIds: ['A'] }];
const concurrent = [{ ...baseline[0], description: 'pool edit', photoIds: ['A', 'B'] }, { id: 'new', description: 'new pool problem' }];
const merged = app.mergeProblemPhotoRecords(concurrent, [{ ...baseline[0], photoIds: ['C'] }], baseline);
assert.deepEqual(copy(merged[0].photoIds), ['B', 'C'], 'local removal and concurrent additions both survive');
assert.equal(merged[0].description, 'pool edit');
assert.equal(merged[1].id, 'new');
assert.deepEqual(copy(app.mergeProblemPhotoRecords([], baseline, baseline)), [], 'unchanged stale draft must not resurrect a deleted problem');
assert.deepEqual(copy(app.mergeProblemPhotoRecords(concurrent, [], baseline)), [concurrent[1]], 'explicit removal must preserve newer independent problems');
sample.problemRecords = [];
app.saveTaskResultDraft({ id: 'p' }, { id: 'stage' }, task, { samples: [{ sid: 's', problemRecords: baseline, problemRecordsBaseline: baseline }] });
assert.deepEqual(copy(task.resultDraft.samples[0].problemRecords), [], 'draft save must not fall back to stale deleted records');
app.photoThumbUrl = photo => photo.url || '';
const html = app.problemPhotoGalleryHtml({ id: 's', photos: [{ id: 'photo_A', name: '<unsafe>', url: '/image' }] }, new Set(['missing']));
assert.ok(html.includes('图片不可用'));
assert.ok(html.includes('&lt;unsafe&gt;'));
assert.ok(html.includes('关联此图'));
assert.ok(!app.problemPhotoGalleryHtml({ id: 's', photos }, new Set(['photo_A']), true).includes('data-photo-choice'));
console.log('PASS problem/image links: draft promotion, stable identity, duplicate merge, attachment-only saves, legacy preservation, row editing, missing images and readonly gallery');
