from __future__ import annotations

from types import SimpleNamespace
from typing import Mapping


HTTP_RUNTIME_FIELDS = (
    "APP_VERSION",
    "DATA_DIR",
    "ROOT_DIR",
    "FRONTEND_DIR",
    "INDEX_PATH",
    "MAX_UPLOAD_BYTES",
    "load_deployment_id",
    "now_iso",
    "build_export_bundle_file",
    "build_remote_export_bundle_file",
    "build_sample_archive_file",
    "first_query_value",
    "get_state",
    "connect_db",
    "compose_bootstrap_state",
    "list_project_summary",
    "load_project_detail",
    "list_sample_categories_summary",
    "list_task_sample_candidates_page",
    "list_sample_destroy_impact_scope",
    "load_sample_category_detail",
    "list_stage_tasks_page",
    "list_samples_page",
    "load_sample_photos",
    "path_inside_data",
    "load_sample_events",
    "list_sample_history_page",
    "analyze_import_bundle",
    "commit_import_bundle",
    "analyze_sample_archive",
    "commit_sample_archive",
    "check_sample_identity_conflicts",
    "parse_multipart",
    "write_sample_asset_file",
    "validate_safe_photo_upload",
    "thumbnail_asset_id",
    "attach_thumbnail_meta",
    "write_db_connection",
    "upsert_sample_asset_meta",
    "commit_sample_asset_mutation",
    "unlink_asset_relative_paths",
    "json_obj",
    "json_dumps",
    "commit_project_mutation",
    "commit_stage_mutation",
    "commit_task_batch_mutation",
    "commit_task_mutation",
    "commit_sample_mutation",
    "commit_sample_category_mutation",
    "save_state",
    "get_access_context",
    "get_project_role",
    "get_pool_role",
    "has_project_role",
    "has_pool_role",
    "project_id_for_stage",
    "project_bound_pool_ids",
    "task_scope",
    "category_id_for_sample",
    "sample_is_linked_to_project",
    "can_read_sample",
    "list_access_rules",
    "upsert_access_rule",
    "delete_access_rule",
    "decorate_project_summaries",
    "decorate_pool_summaries",
    "decorate_bootstrap",
    "access_rule_route",
    "filter_sample_events_for_actor",
    "filter_sample_history_for_actor",
    "sanitize_sample_page_for_actor",
    "sanitize_category_detail_for_actor",
    "filter_photo_list_for_actor",
    "photo_is_visible",
    "sanitize_identity_conflicts",
    "sanitize_destroy_impact",
    "sanitize_task_sample_candidates",
    "record_security_audit_in_transaction",
    "audit_security_event",
    "touch_access_seen",
)


def build_context(namespace: Mapping[str, object]) -> SimpleNamespace:
    missing = [name for name in HTTP_RUNTIME_FIELDS if name not in namespace]
    if missing:
        raise KeyError(f"HTTP runtime context missing fields: {', '.join(missing)}")
    return SimpleNamespace(**{name: namespace[name] for name in HTTP_RUNTIME_FIELDS})
